# Generated by Django 5.1.2 on 2024-10-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="nome")),
                ("birthDate", models.DateField(verbose_name="Nascido em")),
                ("cpf", models.IntegerField(verbose_name="CPF")),
                ("email", models.EmailField(max_length=255, verbose_name="E-mail")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
        ),
    ]
